name: "scheduled"
on:
  # allow manually triggering
  workflow_dispatch:

  # run this every night to make sure nothing breaks
  schedule:
    - cron: "0 0 * * *"

  # run on push to any branch
  push:

# cancel the job if a newer pipeline starts for the same MR or branch
concurrency:
  group: scheduled-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-swift:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./swift
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.1"

      - name: Build
        run: swift build

      - name: Run
        run: swift run

  # run-xcode:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./gradle-java
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - uses: swift-actions/setup-swift@v2
  #       with:
  #         swift-version: "6.0.1"

